### ISSUE TITLE
Available slot remove

### ISSUE THREAD

**Issue by AarohGala** [rikenshah/WolfTutor#45] opened 2018-02-18 01:35 UTC
If a user books a particular time slot, then that time slot should be removed from availability list

**Comment by hhimani** [comment] 2018-02-19 01:09
Working on it.. call back function is not returning the updated value of array elements.

**Comment by hhimani** [comment] 2018-03-02 09:11
So the issue is fixed in the commit "issue 45 and..", the problem was that callback value was returned before the availability flag was updated.

**Closed by hhimani** 2018-03-02 09:11 UTC
Labels: bug
